version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: .docker/Dockerfile.prod
    ports:
      - '8080:8080'
    networks:
      - app-network
    tty: true

  backend:
    build:
      context: ./backend
      dockerfile: .docker/Dockerfile.prod
    volumes:
      - /backend/build
    environment:
      MONGO_URI: mongodb://db:27017/exampledb
    ports:
      - '3000:3000'
    networks:
      - app-network

networks:
  app-network:
    driver: "bridge"

