#
# Build stage
#
FROM node:20-bullseye-slim as build

WORKDIR /app

COPY package*.json ./

RUN npm ci

COPY . .

RUN npm run build

#
# Production stage
#
FROM nginx:1.25-alpine

COPY --from=build /app/build .

EXPOSE 8080

CMD ["nginx", "-g", "daemon off;"]

